### ISSUE TITLE
[Issue]: `is_valid_api_key` needs enhancement 

### ISSUE THREAD

**Issue by qingyun-wu** [autogenhub/autogen#26]
### Describe the issue

The current [`is_valid_api_key`](https://github.com/autogen-ai/autogen/blob/main/autogen/oai/openai_utils.py#L108)  function is dated wrt the latest OpenAI API format. 

It gives the following false alarm:
```
WARNING - The API key specified is not a valid OpenAI format; it won't work with the OpenAI-hosted model.
WARNING:autogen.oai.client:The API key specified is not a valid OpenAI format; it won't work with the OpenAI-hosted model
```

**Comment by marklysze** [comment]
Supporting forum note on [project key lengths changing](https://community.openai.com/t/project-api-key-length-has-it-changed-from-48-to-156/920777).

**Comment by marklysze** [comment]
Please see PR to expand API key format validation, #44
