### ISSUE TITLE
[Bug]: Disk Cache created on import

### ISSUE THREAD

**Issue by omarhurani** [autogenhub/autogen#63]
### Describe the bug

`TextMessageCompressor` creates a disk cache as a default parameter in its constructor, so the disk cache is created on import time, creating a folder.

https://github.com/autogen-ai/autogen/blob/83fe33c8249ee6fef3ce18233a73530c15fff3cb/autogen/agentchat/contrib/capabilities/transforms.py#L328

I had a case where I'm running in a Docker container. I had to create a `.cache` directory with permissions to let the container run even though I am using my own cache implementation elsewhere in the code.

### Steps to reproduce

1. Import the package.
  - `import autogen`
2. A `.cache` folder is created

### Expected Behavior

Disk cache folder should not pop up on `import autogen`.

### Additional Information

AutoGen Version: 0.3.1
Python Version: 3.12.0

**Comment by Hk669** [comment]
@marklysze do you have any idea about this issue?

**Comment by marklysze** [comment]
I haven't looked into it, it seems from @omarhurani's use that it's creating the disk cache independent of what's assigned to the cache.

@omarhurani, how are you instantiating the `TextMessageCompressor` (e.g. what are you setting the cache parameter to or are you leaving it blank)?

**Comment by omarhurani** [comment]
I'm not instantiating it, it gets created when it is imported

**Comment by marklysze** [comment]
Okay, I'll look into it, thanks @omarhurani

**Comment by marklysze** [comment]
@omarhurani, is your only import statement `import autogen`?

E.g. this will create the .cache folder:
```
import autogen
print("Hello")
```

**Comment by marklysze** [comment]
@omarhurani, I've created a PR to move initialisation into the __init__ function, can you test?
#68

**Comment by marklysze** [comment]
Thanks for identifying the bug and testing the fix, @omarhurani, all merged, closing.
